# Generated by Django 4.1.1 on 2022-10-04 12:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfInstallments', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.PositiveIntegerField()),
                ('loanStatus', models.BooleanField(default=False)),
                ('installments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_api.installments')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bankId', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('accountNumber', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_api.user')),
            ],
        ),
    ]
