# Generated by Django 4.1.1 on 2022-10-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installments',
            old_name='datedue',
            new_name='dateDue',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loanAmount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='loanStatus',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='installments',
            name='numberOfInstallments',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='installments',
        ),
        migrations.AddField(
            model_name='installments',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_api.loan'),
        ),
    ]
