# Generated by Django 4.1.1 on 2022-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_rename_datedue_installments_datedue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='number_of_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
