# Generated by Django 4.1.1 on 2022-10-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_loan_number_of_installments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='number_of_installments',
        ),
    ]
