# Generated by Django 4.1.1 on 2022-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0005_remove_loan_number_of_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
