# Generated by Django 4.1.1 on 2022-10-09 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_installments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installments',
            name='dateDue',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
