# Generated by Django 4.1.1 on 2022-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0007_alter_installments_datedue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installments',
            name='amount',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
