# Generated by Django 4.1.1 on 2022-10-10 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0008_alter_installments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installments',
            name='dateDue',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
