# Generated by Django 4.1.1 on 2022-10-10 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0011_alter_installments_datedue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installments',
            name='dateDue',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
