# Generated by Django 4.1.1 on 2022-10-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0013_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_api.loan'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
