# Generated by Django 4.1.1 on 2022-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0014_remove_loan_user_user_loan_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
